[project]
authors = ["the-first-elder"]
entry = "main.sw"
license = "Apache-2.0"
name = "SRC20_standard"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.3" }
